//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::{TransactionTrait, entity::prelude::*, sqlx::database};
use shared::error::ApplicationError;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub parent_category_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentCategoryId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::transaction::Entity")]
    Transaction,
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn find_all(database: &DatabaseConnection) -> Result<Vec<Model>, ApplicationError> {
    Entity::find()
        .all(database)
        .await
        .map_err(|_| ApplicationError::GenericDatabaseError)
}

pub async fn find_by_id(
    category_id: i64,
    database: &DatabaseConnection,
) -> Result<Model, ApplicationError> {
    Entity::find_by_id(category_id)
        .one(database)
        .await
        .map_err(|_| ApplicationError::GenericDatabaseError)
        .and_then(|val| {
            val.ok_or(ApplicationError::ElementNotFound {
                key: category_id.to_string(),
            })
        })
}

pub async fn find_by_path(
    category_path: &[String],
    database: &DatabaseConnection,
) -> Result<Vec<Model>, ApplicationError> {
    let mut parent_id = None;
    let mut actual_category_path: Vec<Model> = Vec::with_capacity(category_path.len());

    for category_name in category_path.iter().map(|name| name.trim()) {
        let parent_condition = match parent_id {
            Some(parent_id) => Column::ParentCategoryId.eq(parent_id),
            None => Column::ParentCategoryId.is_null(),
        };

        let category_model = Entity::find()
            .filter(parent_condition)
            .filter(Column::Name.eq(category_name))
            .one(database)
            .await
            .map_err(|_| ApplicationError::GenericDatabaseError)?;

        let model = match category_model {
            Some(model) => model,
            None => {
                return Err(ApplicationError::CategoryNotFound {
                    category_name: category_name.to_owned(),
                });
            }
        };

        parent_id = Some(model.id);
        actual_category_path.push(model);
    }

    Ok(actual_category_path)
}

pub async fn ensure_path_exists(
    category_path: &[String],
    database: &DatabaseConnection,
) -> Result<Vec<Model>, ApplicationError> {
    let mut parent_id = None;
    let mut response_category_path: Vec<Model> = Vec::with_capacity(category_path.len());

    let txn = database
        .begin()
        .await
        .map_err(|_| ApplicationError::GenericDatabaseError)?;

    for category_name in category_path.iter().map(|name| name.trim()) {
        let parent_condition = match parent_id {
            Some(parent_id) => Column::ParentCategoryId.eq(parent_id),
            None => Column::ParentCategoryId.is_null(),
        };

        let category_model = Entity::find()
            .filter(parent_condition)
            .filter(Column::Name.eq(category_name))
            .one(&txn)
            .await
            .map_err(|_| ApplicationError::GenericDatabaseError)?;

        let model = match category_model {
            Some(model) => model,
            None => {
                use sea_orm::ActiveValue::*;

                ActiveModel {
                    id: NotSet,
                    name: Set(category_name.to_owned()),
                    parent_category_id: Set(parent_id),
                }
                .insert(&txn)
                .await
                .map_err(|_| ApplicationError::GenericDatabaseError)?
            }
        };

        parent_id = Some(model.id);
        response_category_path.push(model);
    }

    txn.commit()
        .await
        .map_err(|_| ApplicationError::GenericDatabaseError)?;

    Ok(response_category_path)
}
