//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::{FromQueryResult, QueryOrder, QuerySelect, entity::prelude::*, raw_sql};
use shared::error::ApplicationError;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "transaction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub change_minor: i64,
    pub category_id: Option<i64>,
    pub reason: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::category::Entity",
        from = "Column::CategoryId",
        to = "super::category::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Category,
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub struct Data {
    pub change_minor: i64,
    pub category_id: Option<i64>,
    pub reason: Option<String>,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

impl From<Data> for ActiveModel {
    fn from(value: Data) -> Self {
        use sea_orm::ActiveValue::*;
        Self {
            id: NotSet,
            change_minor: Set(value.change_minor),
            category_id: Set(value.category_id),
            reason: Set(value.reason),
            created_at: Set(value.created_at.naive_utc()),
        }
    }
}

pub async fn create(
    transaction_data: Data,
    database: &DatabaseConnection,
) -> Result<Model, ApplicationError> {
    ActiveModel::from(transaction_data)
        .insert(database)
        .await
        .map_err(|_| ApplicationError::SpecificDatabaseError {
            reason: "Failed to add a transaction.".to_owned(),
        })
}

pub async fn remove(
    transaction_id: i64,
    database: &DatabaseConnection,
) -> Result<(), ApplicationError> {
    Entity::delete_by_id(transaction_id)
        .exec(database)
        .await
        .map(|_| ())
        .map_err(|_| ApplicationError::SpecificDatabaseError {
            reason: "Failed to delete the transaction.".to_owned(),
        })
}

pub struct Filter {
    /// Inclusive.
    pub created_since: chrono::DateTime<chrono::Utc>,

    /// Exclusive.
    pub created_before: chrono::DateTime<chrono::Utc>,

    pub category_id: Option<i64>,

    pub exclude_subcategories: bool,

    pub limit: Option<u64>,
    pub offset: Option<u64>,
}

pub async fn find_with_filter(
    filter: Filter,
    database: &DatabaseConnection,
) -> Result<Vec<Model>, ApplicationError> {
    let suitable_categories = match filter.category_id {
        Some(category_id) if !filter.exclude_subcategories => {
            Some(resolve_category_subtree(category_id, database).await?)
        }
        Some(category_id) => Some(vec![category_id]),
        None => None,
    };

    let mut select_query = Entity::find()
        .filter(Column::CreatedAt.gte(filter.created_since))
        .filter(Column::CreatedAt.lt(filter.created_before));

    if let Some(categories) = suitable_categories {
        select_query = select_query.filter(Column::CategoryId.is_in(categories));
    }

    if let Some(limit) = filter.limit {
        select_query = select_query.limit(limit).order_by_desc(Column::CreatedAt);
    }

    if let Some(offset) = filter.offset {
        select_query = select_query.offset(offset);
    }

    select_query
        .all(database)
        .await
        .map_err(|_| ApplicationError::GenericDatabaseError)
}

async fn resolve_category_subtree(
    root_category_id: i64,
    database: &DatabaseConnection,
) -> Result<Vec<i64>, ApplicationError> {
    #[derive(FromQueryResult)]
    struct CategoryId {
        id: i64,
    }

    CategoryId::find_by_statement(raw_sql!(
        Sqlite,
        r#"WITH RECURSIVE category_tree (id) AS (
                SELECT id FROM category WHERE id = {root_category_id}

                UNION ALL

                SELECT c.id FROM category c JOIN category_tree ct ON c.parent_category_id = ct.id
            )
            SELECT id FROM category_tree;"#
    ))
    .all(database)
    .await
    .map(|models| models.into_iter().map(|model| model.id).collect())
    .map_err(|_| ApplicationError::GenericDatabaseError)
}
